### ISSUE TITLE
Validation Tooling Checklist

### ISSUE THREAD

**Issue by sunmilee** [diem/reference-wallet#30]
## Simple Transaction Validation
- [x] Direct send
- [x] Direct receive 

## Travel Rule Validation

- Successful transfer
  - Send
    - [x] Immediate travel rule approval
    - [ ] Receiver soft match
    - [ ] Sender soft match
  - Receive
    - [x] Immediate travel rule approval
    - [ ] Receiver soft match
    - [ ] Sender soft match
- Erroneous transfer
  - Handle protocol structure errors in incoming messages
    - [ ] ...
  - Handle protocol consistency errors in incoming messages
    - [ ] Wrong signature
    - [ ] ...
  - Timeouts
    - [ ] KYC response timeout
    - [ ] Response to soft match timeout
    - [ ] Soft mach clearance timeout
    - [ ] Signature timeout
  - Opponent aborts
    - [ ]  Receiver KYC failure
    - [ ]  Receiver KYC failure soft match
    - [ ]  Sender KYC failure
    - [ ]  Receiver KYC failure after soft match
    - [ ]  Signing failure

## Fund Pull Pre-Approval (a.k.a. DIP-8) Validation

- Success scenarios
  - [x] Send pre-approval request
  - [x] Receive pre-approval request
  - [x] Send pre-approval consent (as when getting the request via a QR)
  - [x] Payer approves request
  - [x] Payer rejects pre-approval
  - [x] Payer cancels pre-approval
  - [ ] Payee cancels pre-approval
- Erroneous scenarios
  - [ ] Request with wrong state
  - [ ] Request with expired timestamp
  - [ ] Cancel non-existing pre-approval
- Protocol structure errors
  - [ ] ...
 
## Autherization and Capture

- Success scenarios
  - [ ] Send authorization request
  - [ ] Receive authorization request
  - [ ] Send capture request
  - [ ] Receive capture request 
- Erroneous scenarios
  - [ ] Pre-approval expired
  - [ ] Pre-approval exceeds max cumulative amount
  - [ ] Pre-approval exceeds max transaction amount 
  - [ ] Pre-approval doesn't exist

## KYC implementation 
- [ ] Clear KYC for anyone not in black list
- [ ] Hold an internal list of black-listed users
- [ ] If a user is black-listed, reject the transaction
- [ ] If not all the important fields in KYCDataObject are included, return soft match (even if user is blacklisted)
- [ ] Create endpoint for clearing soft match - clear soft match if we receive any new information in additional_kyc_data
- [ ] (nice to have) Add endpoints to modify black-listed users
